name: Build and release

on:
  push:
    tags:
      - "**"

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout project
        uses: actions/checkout@v4
        with:
          fetch-depth: 50

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore project
        run: |
          dotnet restore

      - name: Build binaries
        run: |
          tag="${{ github.ref_name }}"
          rids=(
            "win-x64"
            "win-x86"
            "linux-x64"
            # "linux-x86" # not supported in the environment
            "osx-x64"
          )
          for rid in "${rids[@]}"
          do
            echo "Publish for ${rid}"
            dotnet publish WoWCombatLogSplit.csproj -c Release -r "${rid}" --output "release/${rid}" --self-contained false /p:PublishSingleFile=true /p:PublishReadyToRun=true
            cd "release/${rid}"
            rm -f .env.example # it's not something most users would use so let's skip it from the release
            rm -f *.pdb # same goes for the debug symbols
            zip -r "../../WoWCombatLogSplit_${tag}_${rid}.zip" .
            cd ../../
          done

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${{ github.ref_name }}"
          gh release create "${tag}" --generate-notes
          gh release upload "${tag}" WoWCombatLogSplit_*.zip

